name: drift_detection_pipeline
steps:
  data_loader:
    source:
      file: steps/data_loader/data_loader_step
      name: data_loader
  data_splitter:
    source:
      file: steps/data_splitter/data_splitter_step
      name: data_splitter
  drift_detector:
    source:
      file: steps/drift_detector/drift_detector_step
      name: drift_detector
  drift_analyzer:
    source:
      file: steps/drift_analyzer/drift_analyzer_step
      name: analyze_drift