fail_fast: true

repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: poetry run bash scripts/lint.sh
        language: system
        files: ^src/zenml/|^tests/|^examples/
        types: [file, python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: docstringcheck
        name: docstringcheck
        entry: poetry run bash scripts/docstring.sh
        language: system
        files: ^src/zenml/
        types: [file, python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run bash scripts/test-coverage-xml.sh unit
        language: system
        files: ^src/zenml/|^tests/
        types: [file, python]
        pass_filenames: false
