steps:
  # login to dockerhub
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-login'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  # build base image
  - name : 'gcr.io/cloud-builders/docker'
    id: 'build-base'
    waitFor: ['docker-login']
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg ZENML_VERSION=$TAG_NAME -t $$USERNAME/zenml:$TAG_NAME -t $$USERNAME/zenml:latest -f docker/base.Dockerfile .']
    secretEnv: ['USERNAME']

  # build CUDA image
  - name : 'gcr.io/cloud-builders/docker'
    id: 'build-cuda'
    waitFor: [ 'docker-login' ]
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg ZENML_VERSION=$TAG_NAME -t $$USERNAME/zenml:$TAG_NAME-cuda -t $$USERNAME/zenml:latest-cuda -f docker/cuda.Dockerfile .']
    secretEnv: ['USERNAME']

  # push the images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    entrypoint: 'bash'
    args: [ '-c', 'docker push $$USERNAME/zenml' ]
    secretEnv: [ 'USERNAME' ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
      env: 'PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
      env: 'USERNAME'
timeout: 3600s
