name: neural_prophet_pipeline
steps:
  data_loader:
    source:
      file: steps/data_loader/data_loader_step
      name: data_loader
  trainer:
    source:
      file: steps/trainer/trainer_step
      name: trainer
  predictor:
    source:
      file: steps/predictor/predictor_step
      name: predictor