name: data_profiling_pipeline
steps:
  data_loader:
    source:
      file: steps
      name: data_loader
  data_splitter:
    source:
      file: steps
      name: data_splitter
  train_data_profiler:
    source:
      file: steps
      name: train_data_profiler
  test_data_profiler:
    source:
      file: steps
      name: test_data_profiler
