name: Feature Request
description: Request a new feature.
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: input
    id: contact
    attributes:
      label: Contact Details [Optional]
      description: How can we get in touch with you if we need more info?
      placeholder: youre@awesome.com
    validations:
      required: false


  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "We can add.."
    validations:
      required: true

  - type: textarea
    id: feature-problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe the problem in detail.
      placeholder: "I'm always frustrated when.."
    validations:
      required: false

  - type: textarea
    id: feature-alternatives
    attributes:
      label: How do you solve your current problem with the current status-quo of ZenML?
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "I considered doing it this other way but this is better because.."
    validations:
      required: false

  - type: textarea
    id: feature-solution
    attributes:
      label: Any other comments?
      description: Add any other context about the feature here.
      placeholder: "This is related to issue #46."
    validations:
      required: false
