apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "zenml.fullname" . }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
data:
  ZENML_DEFAULT_USER_PASSWORD: {{ .Values.zenml.defaultPassword | b64enc | quote }}
  {{- if .Values.zenml.serverId }}
  ZENML_USER_ID: {{ .Values.zenml.serverId | b64enc | quote }}
  {{- else if .Release.IsInstall }}
  ZENML_USER_ID: {{ uuidv4 | b64enc | quote }}
  {{- else }}
  ZENML_USER_ID: {{ (lookup "v1" "Secret" .Release.Namespace (include "zenml.fullname" .)).data.ZENML_USER_ID | default (uuidv4 | b64enc | quote)  }}
  {{- end }}
  {{- if .Values.zenml.jwtSecretKey }}
  ZENML_JWT_SECRET_KEY: {{ .Values.zenml.jwtSecretKey | b64enc | quote }}
  {{- else if .Release.IsInstall }}
  ZENML_JWT_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  ZENML_JWT_SECRET_KEY: {{ (lookup "v1" "Secret" .Release.Namespace (include "zenml.fullname" .)).data.ZENML_JWT_SECRET_KEY | default (randAlphaNum 32 | b64enc | quote) }}
  {{- end }}
  {{- if .Values.zenml.database.url }}
  ZENML_STORE_URL: {{ .Values.zenml.database.url | b64enc | quote }}
  {{- if .Values.zenml.database.sslCa }}
  ZENML_STORE_SSL_CA: {{ .Files.Get .Values.zenml.database.sslCa | b64enc }}
  {{- end }}
  {{- if .Values.zenml.database.sslCert }}
  ZENML_STORE_SSL_CERT: {{ .Files.Get .Values.zenml.database.sslCert | b64enc }}
  {{- end }}
  {{- if .Values.zenml.database.sslKey }}
  ZENML_STORE_SSL_KEY: {{ .Files.Get .Values.zenml.database.sslKey | b64enc }}
  {{- end }}
  {{- end }}