apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenml.fullname" . }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zenml.service.type }}
  ports:
    - port: {{ .Values.zenml.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zenml.selectorLabels" . | nindent 4 }}
