name: training_fashion_mnist
steps:
  importer:
    source:
      file: steps/importers
      name: importer_mnist
  trainer:
    source:
      file: steps/trainers
      name: trainer
    parameters:
      enable_cache: False
  evaluator:
    source:
      file: steps/evaluators
      name: evaluator
  bento_builder:
    source:
      file: steps/bento_builder
      name: bento_builder
  deployment_trigger:
    source:
      file: steps/deployment_trigger_step
      name: deployment_trigger
    parameters:
      min_accuracy: 0.8
  model_deployer:
    source:
      file: steps/deployer
      name: bentoml_model_deployer