name: fashion_mnist_pipeline
steps:
  importer:
    source:
      file: steps/importers
      name: importer_mnist
  trainer:
    source:
      file: steps/trainers
      name: trainer
    parameters:
      enable_cache: False
  evaluator:
    source:
      file: steps/evaluators
      name: evaluator
