name: Docstring Check

on: workflow_call

jobs:
  spellcheck:
    name: docstringcheck
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install interrogate darglint pydocstyle
      - name: Docstring Check
        run: bash scripts/docstring.sh
