name: Linting the Code

on: workflow_call

jobs:
  lint:
    name: lint
    runs-on: ${{ matrix.os }}
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"

    # Exit if its a commit from Gitbook
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

      - name: Install Dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          source $VENV
          zenml integration export-requirements --output-file requirements.txt --ignore-integration feast --ignore-integration label_studio --ignore-integration kserve --ignore-integration bentoml --ignore-integration tekton --ignore-integration airflow
          pip install -r requirements.txt
          rm requirements.txt
          pip install click~=8.0.3
        
      - name: Lint
        run: |
          source $VENV 
          bash scripts/lint.sh