name: 'Pull request reviewer reminder'
on:
  schedule:
    # Check reviews every weekday, 10:00 and 17:00
    - cron: '0 10,17 * * 1-5'
    
jobs:
  pull-request-reviewer-reminder: 
    runs-on: ubuntu-latest
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required
          reminder_message: '1.25 (one and twenty-five hundredths) business days have passed since the review started. Pretty please review the PR.' # Required. Messages to send to reviewers on Github.
          review_turnaround_hours: 30 # Required. This is the deadline for reviews. If this time is exceeded, a reminder will be sent.