name: Trivy ZenServer Scan

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 4 * * 1'  # At 04:00 on Monday

jobs:
  trivy-scan:
    name: Trivy ZenServer scan & analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: zenserver-Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/zenmldocker/zenml-server:latest"
          format: "sarif"
          output: "trivy-results-zenserver.sarif"

      - name: Upload Trivy zenserver scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-zenserver.sarif"
