name: Unit Test & Upload Coverage

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Use tmate session for debugging"
        required: false
        type: boolean
  workflow_call:

jobs:
  unittest:
    name: unittest
    runs-on: ${{ matrix.os }}
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: "utf-8"
      # on MAC OS, we need to set this environment variable
      # to fix problems with the fork() calls (see this thread
      # for more information: http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html)
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES'
    # Exit if it's a commit from Gitbook
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

      - name: Install Prerequisites
        run: |
          source $VENV
          zenml integration export-requirements --output-file requirements.txt kubeflow s3 gcp azure vault pillow evidently deepchecks great_expectations huggingface lightgbm neural_prophet pytorch tensorflow whylogs xgboost mlflow neptune
          pip install -r requirements.txt
          rm requirements.txt
          pip install click~=8.0.3

      - name: Setup tmate session
        if: ${{ github.event.inputs.tags }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: |
          source $VENV
          bash scripts/test-coverage-xml.sh unit

      - name: Upload coverage
        # only do it for python 3.8, we don't need to do it for every version
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
